// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9HyHNpaNx5g96PQZIbFzcm_z958nBV_w',
    appId: '1:260880272383:android:b41d0ad4bd25ff0bdaf5ca',
    messagingSenderId: '260880272383',
    projectId: 'fireecommerce-11e32',
    storageBucket: 'fireecommerce-11e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVnFYKXjzHCyn3_hZbW-8Fhj7jUd85RVg',
    appId: '1:260880272383:ios:ca58ed025bafdd95daf5ca',
    messagingSenderId: '260880272383',
    projectId: 'fireecommerce-11e32',
    storageBucket: 'fireecommerce-11e32.appspot.com',
    iosBundleId: 'com.example.soical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL-oRaGssV771-lPvtr8fgigr55DCdjtk',
    appId: '1:260880272383:web:e8fc7004029886b1daf5ca',
    messagingSenderId: '260880272383',
    projectId: 'fireecommerce-11e32',
    authDomain: 'fireecommerce-11e32.firebaseapp.com',
    storageBucket: 'fireecommerce-11e32.appspot.com',
    measurementId: 'G-T2G3Y75JWL',
  );
}
